---
- name: last time quiz
  hosts: testweb
  vars_files:
    - vars/init_pkg
  tasks:
    - name: install package
      dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ mypkg }}"  

    - name: start web svc 
      service:
        name: nginx
        enabled: true
        state: started
      when: ansible_facts.memtotal_mb > 500 and ansible_facts.ansible_facts.distribution == "Rocky"
